baseURL = 'https://alecsalces.com/'
languageCode = 'en-us'
title = "Alec's Alces"
theme = 'terminal'
[params]
  themeColor = 'green'
  centerTheme = true
  ReadMore = '%>% more()'
  [params.logo]
    logoText = "Alec's Alces"
[menu]
  [[menu.main]]
    name = "About"
    pre = "abt"
    url = "/About/"
    weight = 1
  [[menu.main]]
    name = "Links"
    pre = "lnk"
    url = "/links/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "Categories"
    pre = "categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "Photography"
    pre = "photography"
    url = "/photography/"
    weight = 4
  [[menu.main]]
    name = "Dreams"
    pre = "dreams"
    url = "/dreams"
    weight = 5
  [[menu.main]]
    name = "Dream Tags"
    pre = "dream_tags"
    url = "/dream_tags"
    weight = 6
ignoreFiles = [ "\\.qmd$", "\\.ipynb$", "\\.py$" ]
[markup.goldmark.renderer]
  unsafe= true
[permalinks]
  [permalinks.page]
    posts = '/posts/:slug/'
[taxonomies]
categories = 'categories'
tag = 'tags'
dream_tags = 'dream_tags'
[permalinks.taxonomy]
  tags = '/tags'
  dream_tags = '/dream_tags'
[permalinks.term]
  tags = '/tags/:slug'
  dream_tags = '/dream_tags/:slug'
